export const REQUEST_ALL_QUESTIONS = "REQUEST_ALL_QUESTIONS";
export const SUCCESS_ALL_QUESTIONS = "SUCCESS_ALL_QUESTIONS";
export const FAILURE_ALL_QUESTIONS = "FAILURE_ALL_QUESTIONS";

export const REQUEST_FEATURED_TOPICS = "REQUEST_FEATURED_TOPICS";
export const SUCCESS_FEATURED_TOPICS = "SUCCESS_FEATURED_TOPICS";
export const FAILURE_FEATURED_TOPICS = "FAILURE_FEATURED_TOPICS";
